### ISSUE TITLE
quickstart runme.sh fails

### ISSUE THREAD

**Issue by JoergWende** [ibm-messaging/kafka-connect-elastic-sink#9]
Creating qs_zookeeper_1 ...
Creating qs_elastic_1 ...
Creating qs_zookeeper_1
Creating qs_elastic_1 ... done
Creating qs_kafka_1 ...
Creating qs_kibana_1 ...
Creating qs_kafka_1
Creating qs_kafka_1 ... done
Creating qs_connector_1 ...
Creating qs_connector_1 ... done
Waiting for 60 seconds...
Creating Kafka topic
Publishing to topic

Waiting for 60 seconds...
Transferred documents = null
Failed

**Comment by katheris** [comment]
@JoergWende It looks like from your output that Kibana and zookeeper failed to start up. Can you check your CPU and memory settings of your local Docker? You might need to increase them to allow all the containers to start up correctly.

**Comment by JoergWende** [comment]
I increased the CPU limit to 4 cores but no difference. (memory is dynamic already ...)

**Comment by katheris** [comment]
Once the script has finished what Docker containers do you have running?

**Comment by JoergWende** [comment]
```
CONTAINER ID        IMAGE                                   COMMAND                  CREATED              STATUS              PORTS                                            NAMES
facf51647485        kafka-connect-elastic-sink:latest       "./bin/connect-stand…"   About a minute ago   Up About a minute   0.0.0.0:8083->8083/tcp                           qs_connector_1
97f124a636a2        strimzi/kafka:latest-kafka-2.5.0        "sh -c 'bin/kafka-se…"   About a minute ago   Up About a minute   0.0.0.0:9092->9092/tcp                           qs_kafka_1
5bfedc4ae5e7        docker.elastic.co/kibana/kibana:7.6.0   "/usr/local/bin/dumb…"   About a minute ago   Up About a minute   0.0.0.0:5601->5601/tcp                           qs_kibana_1
b9e97677f5e3        strimzi/kafka:latest-kafka-2.5.0        "sh -c 'bin/zookeepe…"   About a minute ago   Up About a minute   0.0.0.0:2181->2181/tcp                           qs_zookeeper_1
95d2d3a68212        elasticsearch:7.6.0                     "/usr/local/bin/dock…"   About a minute ago   Up About a minute   0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp   qs_elastic_1

```

**Comment by katheris** [comment]
Ok, so that looks like the containers are running to me. What is the output if you now run `curl -k -Ss -H 'Content-Type: application/json' http://localhost:9200/essinktest/_count`

**Comment by JoergWende** [comment]
Going forward and creating the messages manually:
```
docker exec -it qs_kafka_1 /bin/bash
[kafka@d98299a9aeb5 kafka]$  bin/kafka-console-producer.sh --bootstrap-server localhost:9092 --topic ESSINKTEST
>{"Event": "0"}
>{"Event": "1"}
>
```
This results in entries on elastic - but I can't see the payload on kibana 

J.

**Comment by JoergWende** [comment]
with manual entry:

```
curl -k -Ss -H 'Content-Type: application/json' http://localhost:9200/essinktest/_count
{"count":2,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0}}
```

**Comment by katheris** [comment]
Ok, so the connector is working at least. @ibmmqmet do you know any reasons why Kibana might not be able to see the entries in Elastic?

**Comment by JoergWende** [comment]
Hi ... just another information:
this command does not seem to insert any event into the kafka topic - even if returning without errors:
```
docker-compose $project exec -T kafka  \
  /opt/kafka/bin/kafka-console-producer.sh --bootstrap-server kafka:9092 --topic $TOPIC << EOF | sed "s/>//g"
{"Event": "0"}
{"Event": "1"}
{"Event": "2"}
{"Event": "3"}
{"Event": "4"}
{"Event": "5"}
{"Event": "6"}
{"Event": "7"}
{"Event": "8"}
{"Event": "9"}
EOF
```

It works if I run 
```
docker exec qs_kafka_1  /opt/kafka/bin/kafka-console-producer.sh --bootstrap-server kafka:9092 --topic $TOPIC << EOF | sed "s/>//g"
{"Event": "0"}
{"Event": "1"}
{"Event": "2"}
{"Event": "3"}
{"Event": "4"}
{"Event": "5"}
{"Event": "6"}
{"Event": "7"}
{"Event": "8"}
{"Event": "9"}
EOF
```

**Comment by jhughes24816** [comment]
This looks like the issue with the connector was resolved. I will get this closed shortly. If the issue pops up again please open a new issue for it, thanks.
